### ISSUE TITLE
stg_stripe__subscription

### ISSUE THREAD

**Issue by lijol** [fivetran/dbt_stripe_source#48]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

The model is still using stg_stripe__subscription. This is throwing error as the table doesn't not exist . It has been changed to stg_stripe__subscription_history 

### Relevant error log or model output

```shell
STRIPE.SUBSCRIPTION' does not exist or not authorized.
```

### Expected behavior

The model is expected to run fine

### dbt Project configurations

stripe_database: FIVETRAN_DB
stripe_schema: STRIPE

### Package versions

0.7.2

### What database are you using dbt with?

snowflake

### dbt Version

1.1.1

### Are you willing to open a PR to help address this issue?

- [X] Yes.
- [X] Yes, but I will need assistance and will schedule time during our [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance
- [ ] No.

**Comment by lijol** [comment]
As the subscription table is deprecated, isn't it better to have model with subscription _history ?

**Comment by fivetran-joemarkiewicz** [comment]
Hi @lijol the model name is actually `stg_stripe__subscription` (although with the variable it will pull from the history source, but will filter for the latest record). If you try `dbt run -s +stg_stripe__subscription` you should see success. Let me know!

Additionally, I agree that since the non history table has been deprecated it would make sense for the default of that variable to be `true`. However, I believe the deprecation is only for new connectors. Since we have a lot customers still on the older version of the connector, we don't want to break their runs. That being said, we are planning updates to our Stripe package next quarter and will be adjusting the default value of the variable during those next breaking changes!

**Comment by lijol** [comment]
thanks @fivetran-joemarkiewicz this worked.

by default making it true will be very helpful
